### ISSUE TITLE
help.showUI() AttributeError

### ISSUE THREAD

**Issue by nferdazel** [itsthooor/passgen#2]
The program closed when I tried to open the **help** menu.

```
Traceback (most recent call last):
  File "Passgen.py", line 306, in showHelp
    help.showUI()
AttributeError: 'QWidget' object has no attribute 'showUI'
```

**Comment by cheese-wheel-sh** [comment]
Thanks for letting me know.
I'm working on a fix ^^

**Comment by cheese-wheel-sh** [comment]
Fixed the bug and it works now perfectly.
Also added a better UI for the Help.py

**Comment by nferdazel** [comment]
Glad to hear that! You're an awesome developer!

**Comment by cheese-wheel-sh** [comment]
Thank you very much ^^ I'm trying my best :D Also thank you for helping me with finding bugs ^^
